### ISSUE TITLE
Installation process (help needed)

### ISSUE THREAD

**Issue by justchokingaround** [takeiteasy/meh#2]
how can i install and start using meh? there is a .xcodeproj file in the repo that i opened in xcode, but when i ran it, it said build succeeded, but then idk what to do. could you please help me out

**Comment by takeiteasy** [comment]
It's a CLI program so the only way to install it is to copy the built executable to somewhere in your $PATH environment variable. I made this several years ago and haven't really gotten round to working on it, I'd recommend using [this](https://github.com/DrabWeb/macfeh) instead. I believe it can built as an app through Xcode if that's what you're looking for.

**Comment by justchokingaround** [comment]
thank you for the quick reply. i came to your project from macfeh, bc macfeh is very outdated and it can't be built in xcode anymore. i'ld like to avoid xcode at all costs actually. if i understood correctly i just need to copy project.pbxproj to my /usr/local/bin and it should work? or what is the built executable exactly? (i come from linux, so mac development is new to me)

**Comment by takeiteasy** [comment]
You can either build it from terminal by negating to (where you saved the project) and running the command "clang meh.m -x objective-c -framework Cocoa -o meh" then copy the executable called "meh" in the project folder, to your $PATH or alternatively open the xcodeproj, hit build, then on the side column under a folder called "Products" will be an executable called "meh", right click on it, Show in Finder then copy that $PATH.

There isn't a help dialog atm, I didn't get around to it, but there are few arguments you can use when running, but I don't think any are especially import or even implemented so I wouldn't worry about them, just run meh <image paths>. Good luck, because it's certainly not finished and will like crash a lot.

**Comment by justchokingaround** [comment]
<img width="1394" alt="Screenshot 2022-03-20 at 15 50 01" src="https://user-images.githubusercontent.com/44473782/159168254-1c31e352-0f2e-4331-8918-e8b1ca6dd9da.png">
well, i got 4 warning generated after compiling it, and after adding the executable to path it worked fine, except the keybinds, none of those worked. unfortunately idk anything about C, so i can't really those deprecated warnings

**Comment by takeiteasy** [comment]
Yeah, they old deprecated methods still work, but may be phased out in future releases of Mac OS. Sorry about the state I left this in, I might get around to updating it eventually, but I'm quite busy at the moment so I couldn't say when.
